
USE hospital_db;

SELECT * FROM hospital_db.Healthcare_dataset;

-- 1. Count of patients by gender
SELECT gender, COUNT(*) AS total_patients
FROM healthcare_dataset
GROUP BY gender;

-- 2. Most common diagnoses
SELECT diagnosis, COUNT(*) AS frequency
FROM healthcare_dataset
GROUP BY diagnosis
ORDER BY frequency DESC;

-- 3. Total and average bill amount per hospital
SELECT HospitalName, COUNT(*) AS total_patients, 
       SUM(BillAmount) AS total_billing, 
       AVG(BillAmount) AS avg_billing
FROM healthcare_dataset
GROUP BY HospitalName
ORDER BY total_billing DESC;

-- 4. Age distribution of patients
SELECT 
  CASE 
    WHEN age BETWEEN 0 AND 18 THEN '0-18'
    WHEN age BETWEEN 19 AND 35 THEN '19-35'
    WHEN age BETWEEN 36 AND 50 THEN '36-50'
    WHEN age BETWEEN 51 AND 65 THEN '51-65'
    ELSE '66+' 
  END AS age_group,
  COUNT(*) AS total
FROM healthcare_dataset
GROUP BY age_group
ORDER BY age_group;

-- 5. Average stay duration per hospital
SELECT HospitalName,
       AVG(DATEDIFF(DischargeDate,AdmissionDate)) AS avg_stay_days
FROM healthcare_dataset
GROUP BY HospitalName;

-- 6. Revenue generated by each doctor
SELECT DoctorName, 
       SUM(BillAmount) AS total_revenue, 
       COUNT(*) AS patients_treated
FROM healthcare_dataset
GROUP BY DoctorName
ORDER BY total_revenue DESC;

-- 7. Top 5 treatments by frequency
SELECT Treatment, COUNT(*) AS count
FROM healthcare_dataset
GROUP BY treatment
ORDER BY count DESC
LIMIT 5;

-- 8. Monthly patient admission trends
SELECT DATE_FORMAT(admissiondate,'%Y-%m') AS month, 
       COUNT(*) AS admissions
FROM healthcare_dataset
GROUP BY month
ORDER BY month;
